### ISSUE TITLE
Story::As a candidate, I would like to be reminded about the current summary(especially the unanswered questions) when I try to finish the exam before answering all the questions

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#12]
- [ ] API/Method to check whether all the questions are answered https://github.com/rkulkar5/OnlineTAT/issues/19
- [ ] Adding Finish Button to the last question screen of the test. (is blocked by https://github.com/rkulkar5/OnlineTAT/issues/16)
- [ ] Both the UI and Method to enable warning screen to be displayed - when the candidate tries to finish test without answering all questions - see the screen below for the warning content - (also blocked by https://github.com/rkulkar5/OnlineTAT/issues/18)
- [ ] Enable an option to go back to the previous question. 
- [ ] Enable a way to click and go to any questions in the summary.

**Comment by Adharshd** [comment]
As shown below the last question should have a Finish Button
![Q4-Answer](https://user-images.githubusercontent.com/8875515/76832443-52424000-684f-11ea-8f8b-d20772e106e7.png)

The warning to be displayed when the candidate tries to finish without answering all questions. 
![Finish the test](https://user-images.githubusercontent.com/8875515/76832693-d8f71d00-684f-11ea-81ad-db7e60463704.png)
